/*
 * @Author: linqibin
 * @Date: 2023-11-28 10:26:02
 * @LastEditors: linqibin
 * @LastEditTime: 2023-12-04 18:01:04
 * @Description: 
 * 
 * Copyright (c) 2023 by @https://github.com/Issho-lin, All Rights Reserved. 
 */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NProgressProvider from "@/provider/Nprogress";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NProgressProvider>{children}</NProgressProvider>
      </body>
    </html>
  );
}
